### ISSUE TITLE
Create "Error" data type

### ISSUE THREAD

**Issue by mihail-stanchev** [ChaosGroup/json-ws#30]

**Comment by psstoev** [comment]
After the initial implementation we stumbled on the following issue: The "error" datatype as it is now is useful only when you are "returning" error from JSON-WS server, when you try to pass it as an argument if you pass `Error` instance you will send empty object to the server, because `JSON.stringify(new Error('?'))` results in `"{}"`. We will hit a similar problem when we try to implement a `Map` datatype - #28. There is no good solution to this - we should either drop these new type, monkey-patch `Error.prototype` to add `toJSON` method (yikes), or use a custom serializer for `JSON.stringify()` in `lib/client.js`. We should benchmark the last option to check for performance penalties and fallback to opt-in monkey-patching if the performance is not acceptable.

**Comment by mihail-stanchev** [comment]
...or implement proper conversion functions?
